/*
 Copyright (c) 2014, Pixel & Tonic, Inc.
 @license   http://craftcms.com/license Craft License Agreement
 @see       http://craftcms.com
 @package   craft.app.resources
*/
(function(a){Craft.AccountSettingsForm=Garnish.Base.extend({userId:null,isCurrent:null,$copyPasswordResetUrlBtn:null,$actionSpinner:null,currentPasswordModal:null,$lockBtns:null,$currentPasswordInput:null,$currentPasswordSpinner:null,afterVerifyPassword:null,currentPassword:null,confirmDeleteModal:null,$deleteBtn:null,init:function(d,b){this.userId=d;this.isCurrent=b;this.$lockBtns=a(".btn.lock");this.$copyPasswordResetUrlBtn=a("#copy-passwordreset-url");this.$actionSpinner=a("#action-spinner");this.$deleteBtn=
a("#delete-btn");this.addListener(this.$lockBtns,"click","showCurrentPasswordForm");this.addListener(this.$copyPasswordResetUrlBtn,"click","getPasswordResetUrl");this.addListener(this.$deleteBtn,"click","showConfirmDeleteModal")},showCurrentPasswordForm:function(){if(this.currentPasswordModal)this.currentPasswordModal.show();else{var d=this.isCurrent?Craft.t("Please enter your current password."):Craft.t("Please enter your password."),b=a('<form id="verifypasswordmodal" class="modal fitted"/>').appendTo(Garnish.$bod),
c=a('<div class="body"><p>'+d+"</p></div>").appendTo(b),d=a('<div class="passwordwrapper"/>').appendTo(c),c=a('<div class="buttons right"/>').appendTo(c),f=a('<div class="btn">'+Craft.t("Cancel")+"</div>").appendTo(c);a('<input type="submit" class="btn submit" value="'+Craft.t("Continue")+'" />').appendTo(c);this.$currentPasswordInput=a('<input type="password" class="text password fullwidth"/>').appendTo(d);this.$currentPasswordSpinner=a('<div class="spinner hidden"/>').appendTo(c);this.currentPasswordModal=
new Garnish.Modal(b,{onHide:a.proxy(function(){this.afterVerifyPassword=null},this)});new Craft.PasswordInput(this.$currentPasswordInput,{onToggleInput:a.proxy(function(a){this.$currentPasswordInput=a},this)});this.addListener(f,"click",function(){this.currentPasswordModal.hide()});this.addListener(b,"submit","submitCurrentPassword")}Garnish.isMobileBrowser(!0)||setTimeout(a.proxy(function(){this.$currentPasswordInput.focus()},this),100)},submitCurrentPassword:function(d){d.preventDefault();var b=
this.$currentPasswordInput.val();b&&(this.$currentPasswordSpinner.removeClass("hidden"),Craft.postActionRequest("users/verifyPassword",{password:b},a.proxy(function(c,d){this.$currentPasswordSpinner.addClass("hidden");if("success"==d)if(c.success){this.currentPassword=b;a('<input type="hidden" name="password"/>').val(b).appendTo("#userform");var e=a("#newPassword");a("#email").add(e).removeClass("disabled").removeAttr("disabled");this.$lockBtns.remove();new Craft.PasswordInput(e);this.afterVerifyPassword&&
this.afterVerifyPassword();this.currentPasswordModal.hide()}else Garnish.shake(this.currentPasswordModal.$container)},this)))},getPasswordResetUrl:function(){this.currentPassword?(this.$actionSpinner.removeClass("hidden"),Craft.postActionRequest("users/getPasswordResetUrl",{password:this.currentPassword,userId:this.userId},a.proxy(function(a,b){this.$actionSpinner.addClass("hidden");if("success"==b){var c=Craft.t("{ctrl}C to copy.",{ctrl:navigator.appVersion.indexOf("Mac")?"\u2318":"Ctrl-"});prompt(c,
a)}},this))):(this.afterVerifyPassword=a.proxy(this,"getPasswordResetUrl"),this.showCurrentPasswordForm())},showConfirmDeleteModal:function(){this.confirmDeleteModal?this.confirmDeleteModal.show():this.confirmDeleteModal=new Craft.DeleteUserModal(this.userId)}})})(jQuery);

//# sourceMappingURL=AccountSettingsForm.min.map
